version: '3.4'

services:
  mongodb:                    
    container_name: mongo     
    image: mongo    
    ports:                    
      - 8017:27017
  
  flask:                      
    container_name: flask   
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002
    links:                                     
      - mongodb 

      